addSbtPlugin("com.github.sbt"  % "sbt-release"         % "1.4.0")
addSbtPlugin("com.github.sbt"  % "sbt-native-packager" % "1.11.7")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"        % "2.5.6")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"        % "0.12.1")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"       % "2.2.2")
